
name: Copy_firmware

on:
  workflow_dispatch:  # Manually start a workflow
  push:
    branches: main
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  firmware_pull:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Copy Tasmota firmware
      run: |
        git config --local user.name "Platformio BUILD"
        git config user.email github-actions@github.com
        git remote add -f Tasmota "https://github.com/arendst/Tasmota.git" --track firmware_delete
        git config merge.renameLimit 999999
        git pull upstream main --allow-unrelated-histories
        git push origin main
        git merge Tasmota/firmware_delete --allow-unrelated-histories
